version: '3.8'

services:
  mysql9:
    image: mysql:9.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root      
      MYSQL_DATABASE: library_db               
      MYSQL_USER: library_user                  #username for the user 
      MYSQL_PASSWORD: user          #Password for the non-root user
    volumes:
      - ./mysql-data:/var/lib/mysql             #persist mysql9 data in a volume
      - ./mysql_scripts:/docker-entrypoint-initdb.d  #run the sql script to create the init database/tables 

  ubuntu-app:
    build:
      context: .
      dockerfile: Dockerfile                    # the ubuntu build gonna be made from the ./Dockerfile
    depends_on:
      - mysql9                                   # if the mysql container if its running correctly only then run the proceed for the second container 
    environment:
      DB_HOST: mysql9                            
      DB_PORT: 3306                             
      DB_NAME: library_db                       
      DB_USER: library_user                     
      DB_PASSWORD: user            
    volumes:
      - ./libraryApp:/usr/src/app                  
    tty: true    # keep the conainer running interactively